# Generated by Django 5.2.8 on 2025-11-12 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stock_units', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stock_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='core.family')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='core.store')),
            ],
            options={
                'ordering': ['store__code', 'family__familia_std', 'family__subfamilia_std', 'date'],
                'indexes': [models.Index(fields=['store', 'date'], name='stock_stock_store_i_688b59_idx'), models.Index(fields=['family', 'date'], name='stock_stock_family__7ad9b8_idx')],
                'unique_together': {('store', 'family', 'date')},
            },
        ),
    ]
