# Generated by Django 5.2.8 on 2025-12-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_family_core_family_origen_3151b7_idx_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockrecord',
            index=models.Index(fields=['store', 'family', 'date'], name='stock_stock_store_i_1e8be2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockrecord',
            index=models.Index(fields=['date'], name='stock_stock_date_b0e748_idx'),
        ),
    ]
