# Generated by Django 5.2.8 on 2025-11-12 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('units_sold', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.family')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.store')),
            ],
            options={
                'ordering': ['store__code', 'family__familia_std', 'family__subfamilia_std', 'date'],
                'indexes': [models.Index(fields=['store', 'date'], name='sales_sales_store_i_226712_idx'), models.Index(fields=['family', 'date'], name='sales_sales_family__9e00ad_idx')],
                'unique_together': {('store', 'family', 'date')},
            },
        ),
    ]
