# Generated by Django 5.2.8 on 2025-12-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_family_core_family_origen_3151b7_idx_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['store', 'family', 'date'], name='sales_sales_store_i_4f43c4_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['date'], name='sales_sales_date_28923e_idx'),
        ),
    ]
