# Generated by Django 5.2.8 on 2025-11-12 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.region')),
            ],
            options={
                'ordering': ['region__name', 'name'],
                'unique_together': {('region', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('is_distribution_center', models.BooleanField(default=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='core.region')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='core.zone')),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='core_store_code_a420d8_idx'), models.Index(fields=['region', 'zone'], name='core_store_region__ca9003_idx')],
            },
        ),
    ]
