# Generated by Django 5.2.8 on 2025-11-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=80)),
                ('sector', models.CharField(max_length=80)),
                ('familia_std', models.CharField(max_length=120)),
                ('subfamilia_std', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['origen', 'sector', 'familia_std', 'subfamilia_std'],
                'unique_together': {('origen', 'sector', 'familia_std', 'subfamilia_std')},
            },
        ),
    ]
