# Generated by Django 5.2.8 on 2025-12-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_family'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['origen', 'is_active'], name='core_family_origen_3151b7_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['is_active'], name='core_family_is_acti_23a52b_idx'),
        ),
    ]
